language: node_js
node_js:
- 0.1
- 0.11
env:
  global:
    secure: Hiq4/1Q5wc1T+Q0/OUO4vGjDlp0JIgpNMshJLjQ7kPiI91nKWgQ8crTfm5yntbt4/g7mcDDK87Pqm8RMFVeVKGYD2tcswc01tn9d2MWKLR830mx9ys8fB5cwiebzZD/GaRjN8VMgnYsiVk+5xNboccuYqckG8EelrqcJp6NI6dM=
